#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:
    
services:
  ilearning_page_admin_v1:
    container_name: {CONTAINER_NAME}
    image: {CONTAINER_IMAGE}:1.0
    restart: always
    mem_limit: 200m
    networks:
        - basic
    ports:
      - "192.168.0.10:{PORT}:{PORT}"
    #tty: true
    #command: /bin/bash
